/* 
Copyright (C) 2009-2010 Parvez Ahmad
Written by Parvez Ahmad <parvez_ahmad@yahoo.co.uk>.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.  */

#ifndef _PARSEINCLUDE_H_
#define _PARSEINCLUDE_H_
#include "always.h"
#include "assign.h"
#include "basednum.h"
#include "base.h"
#include "binexpr.h"
#include "bitsel.h"
#include "blockdecl.h"
#include "block.h"
#include "case.h"
#include "cntv.h"
#include "compassign.h"
#include "concat.h"
#include "condexpr.h"
#include "const.h"
#include "contassign.h"
#include "dassign.h"
#include "defines.h"
#include "defparam.h"
#include "delay.h"
#include "dimension.h"
#include "disable.h"
#include "elaborator.h"
#include "event.h"
#include "expr.h"
#include "file.h"
#include "finderonpath.h"
#include "force.h"
#include "fork.h"
#include "gateinst.h"
#include "generate.h"
#include "hierid.h"
#include "if.h"
#include "initial.h"
#include "inst.h"
#include "intconst.h"
#include "integer.h"
#include "ixname.h"
#include "localparam.h"
#include "loopstmts.h"
#include "modinst.h"
#include "module.h"
#include "multiconcat.h"
#include "namedblockbase.h"
#include "namedblock.h"
#include "net.h"
#include "num.h"
#include "omcreator.h"
#include "omvisitor.h"
#include "param.h"
#include "parsehelp.h"
#include "parseinfo.h"
#include "partsel.h"
#include "path.h"
#include "pin.h"
#include "port.h"
#include "procassign.h"
#include "proccontassign.h"
#include "range.h"
#include "realconst.h"
#include "real.h"
#include "realtime.h"
#include "reg.h"
#include "root.h"
#include "scalarcntv.h"
#include "scope.h"
#include "semcheck.h"
#include "specify.h"
#include "stmtcont.h"
#include "stmt.h"
#include "taskfunc.h"
#include "vtime.h"
#include "trigger.h"
#include "udp.h"
#include "udpinst.h"
#include "unaryexpr.h"
#include "utils.h"
#include "var.h"
#include "veccntv.h"
#include "vecint.h"
#include "veclocalparam.h"
#include "vecnet.h"
#include "vecparam.h"
#include "vecpin.h"
#include "vecport.h"
#include "vecreal.h"
#include "vecrealtime.h"
#include "vecreg.h"
#include "vectime.h"
#include "vecvar.h"
#include "vlist.h"
#include "vstring.h"
#endif
